site_name: Fiori Tracker
site_url: https://help.fioritracker.org/V2020/
nav:
    - Suite: suite/SPS03/main.md
    - Tracked content:    
      - Roles: tracked/SPS03/roles.md
      - Catalogs: tracked/SPS03/cats.md
      - Apps: tracked/SPS03/apps.md
      - Apps usage: tracked/SPS03/appsusage.md
      - Systems: tracked/SPS03/systems.md
      - Sign-offs: tracked/SPS03/signoff.md
      - Change requests: tracked/SPS03/changereq.md
      - Security checks: tracked/SPS03/gover.md
      - Test users: tracked/SPS03/testusers.md
      - Comments: tracked/SPS03/comments.md
    - Use cases:
      - Gathering requirements: usecases/SPS03/requirements-gathering/
    - Available components:
      - Core:
        - Fiori Tracker Core: core/SPS03/main.md
        - Extensions: core/SPS03/ext.md
        - Relations: core/SPS03/rel.md
      - Roles: ro/FPS01/main.md    
      - Catalog and App Reports: cat-app/SPS02/main.md 
      - Change Requests: ch/FPS01/main.md
      - Sign-offs: so/FPS01/main.md
      - Test users: tu/FPS01/main.md
      - Gover ðŸŒ±: gv/FPS01/main.md
      - As-is API: asis/SPS02/main.md
    - Installation: inst.md
    - Minimal requirements: inst/min.md        
    - Bugs and ideas: bugs-ideas.md
    - Premier Support: premier.md
    - FAQ: faq.md
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css  
markdown_extensions:
  - admonition  
plugins:
  - macros
  - search
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/fiori-tracker/
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/fioritracker
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC6bx5QiaM3KRE8qgshBrurg
  prod:  
    core:
      name: 'Fiori Tracker Core'
      main: '2020'
      latestrel: 'SPS03'
      cen: 'X'
      man: ' '
      rep: 'installation'
      pay: 'free'
    asisCen:
      name: 'As-is main: API'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'asis-cen'
      pay: 'free'
    asisMan:
      name: 'As-is Connector'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: 'X'
      rep: 'asis-man'
      pay: 'free'
    cr:
      name: 'Catalog Report'
      main: '2020'
      latestrel: 'SPS02'
      cen: 'X'
      man: ' '
      rep: 'cat-rep'
      pay: 'free'
    ac:
      name: 'App Catalogs Report'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ac'
      pay: 'free'
    ca:
      name: 'Catalog Apps Report'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ca'
      pay: 'free'
    fa:
      name: 'Fiori Apps Usage Report'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'fa'
      pay: 'paid'
    fap:
      name: 'Fiori Apps Usage Plugin'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: 'X'
      rep: 'fap'
      pay: 'paid'
    ftCatsRelAppsAsis:
      name: 'FT Catalogs Relation: Apps As-is'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'asis-cen'
      pay: 'free'
    ftAppsRelCatsAsis:
      name: 'FT Apps Relation: Catalogs, As-is'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'asis-cen'
      pay: 'free'
    ftAppsRelAppsUsage:
      name: 'FT Apps Relation: Apps` Usage'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'fa'
      pay: 'paid'
    ch:
      name: 'Change Requests'
      desc: 'The Change Request app lets you create, change and list the change request linked to catalogs and apps.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ch'
      pay: 'free'
    RelCh:
      name: 'FT Apps and Catalogs Relation: Change Requests'
      desc: 'The Change Request relation shows a list of change requests linked to an application or catalog.'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ch'
      pay: 'free'  
    so:
      name: 'Sign-offs'
      desc: 'The Sign-offs app lets you create, change and list sign-offs records linked to all content types (apps, catalogs and roles)'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'so'
      pay: 'free'
    RelSo:
      name: 'FT Apps and Catalogs Relation: Sign-offs'
      desc: 'The Sign-offs relation shows a list of sign-offs linked to all content types (apps, catalogs and roles)'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'so'
      pay: 'free'
    ro:
      name: 'Fiori Tracker Roles'
      desc: 'Roles'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ro'
      pay: 'free'
    RelRo:
      name: 'FT Apps and Catalogs Relation: Roles'
      desc: 'The Roles relation shows a list of sign-offs linked to all content types (apps, catalogs and roles)'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ' '
      rep: 'ro'
      pay: 'free'

